# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Poems for Pessimistic Seniors"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/vickylaiio/hugo-theme-introduction/blob/master/LICENSE.md"
description = "Minimal, single page, smooth scrolling theme for Hugo."
homepage = "https://github.com/vickylaiio/hugo-theme-introduction"
tags = ["clean", "minimal"]
features = ["responsive", "single page"]
min_version = 0.15

[author]
  name = "Vicky Lai"
  homepage = "https://vickylai.io"

# If porting an existing theme
[original]
  name = "Pam Williams"
  homepage = ""
  repo = ""
