baseurl             = "http://pessimisticpoems.com/"
languageCode        = "en-us"
title               = "Poems for Pessimistic Seniors"
theme               = "introduction"
enforce_ssl         = "pessimisticpoems.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "docs"
disqusshortname   = "ppoems" # Enable Disqus for comments
googleAnalytics   = "UA-99145474-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "Pam" # Full name shows on blog post pages
firstname     = "A Pessimist" # First name shows in introduction on main page
tagline       = "writing poems for other pessimistic seniors." # Appears after the introduction
introheight   = "small" # Input either 'medium' or 'large' or 'fullheight'
theme         = "light" # Choose 'light' or 'dark'
avatar        = "" # Path to image in static folder eg. img/avatar.png
email         = "" # Shows in contact section, or leave blank to omit
localtime     = true # Show your current local time in contact section
timezone      = "America/Los_Angeles" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = ""
faviconfile   = "img/fav.ico"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "" # Text to show in footer (overrides default text)

fadein          = true # Turn on/off the fade-in effect

showblog        = true # Show Blog section on home page
showallposts    = true # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showcontact     = false
showabout       = true
showprojects    = false # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
#project1link    = ""
#project1img     = ""
#project1title   = "Project 1"


# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

#[[params.social]]
#url = "https://twitter.com/"
#icon = "twitter"

[blackfriday]
extensions = ["hardLineBreak"]
